// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Для migrate используй LOCAL_DATABASE_URL (file:./prisma/dev.db).
// Иначе — DATABASE_URL (Turso). См. docs/TURSO_MIGRATIONS.md
const dbUrl =
  process.env["LOCAL_DATABASE_URL"] ?? process.env["DATABASE_URL"] ?? "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
